import { LitElement, html, css } from "lit";
import { customElement, property, state } from "lit/decorators.js";
import { unsafeHTML } from "lit/directives/unsafe-html.js";
import mermaid from "mermaid";

mermaid.initialize({
  startOnLoad: false,
});

let nextId = 0;

@customElement("rp-mermaid")
export class RpMermaid extends LitElement {
  static override styles = css`
    :host {
      display: block;
      margin: 0.5em 0;
      overflow-x: auto;
      background: var(--code-bg);
      border: 1px solid var(--code-border);
      border-radius: 4px;
      padding: 1rem;
    }
    .error {
      color: var(--diff-del-text);
      font-family: monospace;
      white-space: pre-wrap;
    }
  `;

  @property({ type: String }) code = "";
  @property({ type: String }) theme = "dark";

  @state() private _svg = "";
  @state() private _error = "";

  override willUpdate(changedProperties: Map<PropertyKey, unknown>) {
    if (changedProperties.has("code") || changedProperties.has("theme")) {
      void this._renderDiagram();
    }
  }

  private async _renderDiagram() {
    if (!this.code.trim()) {
      this._svg = "";
      this._error = "";
      return;
    }

    const id = `mermaid-svg-${String(nextId++)}`;
    try {
      mermaid.initialize({
        startOnLoad: false,
        theme: this.theme === "dark" ? "dark" : "default",
      });
      const { svg } = await mermaid.render(id, this.code);
      this._svg = svg;
      this._error = "";
    } catch (err) {
      this._error = err instanceof Error ? err.message : String(err);
      // Clean up DOM elements generated by mermaid inside document body
      const badEl = document.getElementById(id);
      if (badEl) badEl.remove();
      const bindEl = document.getElementById(`d${id}`);
      if (bindEl) bindEl.remove();
    }
  }

  override render() {
    if (this._error) {
      return html`<div class="error">Mermaid Error: ${this._error}</div>`;
    }
    return html`${unsafeHTML(this._svg)}`;
  }
}
